routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
	/**
	 * Profile routes
	 */
	Route::prefix('profile')->group(function() {
		Route::get('edit', 'ProfileController@edit')->name('profile.edit');
		Route::put('edit', 'ProfileController@update')->name('profile.update');
		Route::put('password', 'ProfileController@password')->name('profile.password');
	});

	Route::middleware('admin')->group(function() {
		Route::resource('user', 'UserController');
		Route::resource('group', 'UserGroupController');
	});

	/**
	 * Project routes
	 */
	Route::resource('project', 'ProjectController');
	Route::prefix('project')->group(function() {
		
		/**
		 * Contributor routes
		 */
		Route::get('{id}/contributor', 'ProjectContributorController@index')->name('contributor.index');
		Route::post('{id}/contributor', 'ProjectContributorController@store')->name('contributor.store');
		Route::delete('{id}/contributor/{contrib_id}', 'ProjectContributorController@destroy')->name('contributor.destroy');

		/**
		 * Timeline routes
		 */
		Route::get('{id}/timeline', 'ProjectTimelineController@index')->name('timeline.index');
		Route::get('{id}/timeline/create', 'ProjectTimelineController@create')->name('timeline.create');
		Route::post('{id}/timeline', 'ProjectTimelineController@store')->name('timeline.store');
		Route::get('{id}/timeline/{timeline_id}', 'ProjectTimelineController@edit')->name('timeline.edit');
		Route::put('{id}/timeline/{timeline_id}', 'ProjectTimelineController@update')->name('timeline.update');
		Route::delete('{id}/timeline/{timeline_id}', 'ProjectTimelineController@destroy')->name('timeline.destroy');

		// Approve timeline
		Route::get('{id}/timeline/{timeline_id}/approve', 'ProjectTimelineController@toggleApprove')->name('timeline.approve');
		
		// Child timeline
		Route::post('{id}/timeline/child', 'ProjectTimelineController@storeChild')->name('timeline.child.store');

		/**
		 * Timeline comments
		 */
		Route::post('{id}/timeline/{timeline_id}/comment', 'ProjectTimelineCommentController@store')->name('timeline.comment.store');
		Route::delete('{id}/timeline/{timeline_id}/comment/{comment_id}', 'ProjectTimelineCommentController@destroy')->name('timeline.comment.destroy');
	});
});

resources/views/home.blade.php
@extends('layouts.landing')

@section('content')
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-primary mb-0">Welcome Back</h2>
            <h1 class="display-2">{{ Auth::user()->name }}</h1>

            <div class="form-group my-3">

                <div class="input-group input-group-alternative">
                    <input type="search" name="keyword" id="keyword" class="form-control form-control-alternative" placeholder="Search for a project">

                    <div class="input-group-append">
                        <button class="btn btn-primary">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>

            <div class="d-flex align-items-center mt-5 mb-3">
                <h1>Recent Projects</h1>
                <a href="{{ route('project.create') }}" class="btn btn-success btn-icon ml-auto">
                    <span class="btn-inner--icon"><i class="ni ni-diamond"></i></span>
                    <span class="btn-inner--text">New project</span>
                </a>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @if (session('status'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ session('status') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                </div>

                @if ($projects->isNotEmpty())
                    @foreach ($projects as $p)
                        <div class="col-md-6">
                            <div class="card border shadow-sm mb-4">
                                <div class="card-body">
                                    <h2 class="card-title">
                                        {{ $p->name }}

                                        @if ($p->date_due->diffInDays(now()) < 2)
                                            <span class="badge badge-danger">
                                                {{ $p->date_due->diffForHumans() }}
                                            </span>
                                        @elseif ($p->date_due->diffInDays(now()) < 7)
                                            <span class="badge badge-warning">
                                                {{ $p->date_due->diffForHumans() }}
                                            </span>
                                        @else
                                            <span class="badge badge-success">
                                                {{ $p->date_due->diffForHumans() }}
                                            </span>
                                        @endif
                                    </h2>

                                    <h5 class="card-subtitle text-muted">
                                        Started by <a href="">{{ $p->started_by->name }}</a>
                                    </h5>
                                    
                                    <div class="row justify-content-center pt-5">
                                        <div class="col-md-4 text-center">
                                            <div class="icon icon-shape bg-gradient-blue text-white rounded-circle shadow icon-detail">
                                                <i class="fa fa-percentage"></i>
                                            </div>
                                            <div class="py-3">
                                                <span class="font-weight-bold">
                                                    {{ $p->done_percentage() }}
                                                </span>
                                                Done
                                            </div>
                                        </div>
                                        <div class="col-md-4 text-center">
                                            <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow icon-detail">
                                                <i class="fa fa-project-diagram"></i>
                                            </div>
                                            <div class="py-3">
                                                {{ $p->timelines->count() . Str::plural(" Timeline", $p->timelines->count()) }}
                                            </div>
                                        </div>
                                        <div class="col-md-4 text-center">
                                            <div class="icon icon-shape bg-gradient-success text-white rounded-circle shadow icon-detail">
                                                <i class="fa fa-users"></i>
                                            </div>
                                            <div class="py-3">
                                                {{ $p->contributors->count() . Str::plural(" Contributor", $p->contributors->count()) }}
                                            </div>
                                        </div>
                                    </div>
        
                                    <div class="d-flex align-items-baseline">
                                        <div class="mt-4">
                                            Due date
                                            @if ($p->date_due->diffInDays(now()) < 2)
                                                <span class="text-danger">
                                                    {{ date('d M Y', strtotime($p->date_due)) }}
                                                </span>
                                            @elseif ($p->date_due->diffInDays(now()) < 7)
                                                <span class="text-warning">
                                                    {{ date('d M Y', strtotime($p->date_due)) }}
                                                </span>
                                            @else
                                                <span class="text-success">
                                                    {{ date('d M Y', strtotime($p->date_due)) }}
                                                </span>
                                            @endif
                                        </div>

                                        <a href="{{ route('project.show', $p->id) }}" class="btn btn-success bg-gradient-success ml-auto btn-icon">
                                            <span class="btn-inner--icon"><i class="ni ni-app"></i></span>
                                            <span class="btn-inner--text">
                                                Go to project
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                @else
                    <div class="col-md-12 mt-4">
                        <div class="text-danger text-center">
                            No projects found.
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script>
    var toggle = false;
    var animationClass = 'pulse';

    $('.card').hover(function() {
        toggle = !toggle;

        if (toggle) {
            $('.icon-detail').addClass(animationClass + " animated");
        } else {
            $('.icon-detail').removeClass(animationClass + " animated");
        }
    });
</script>
@endpush