routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
	/**
	 * Profile routes
	 */
	Route::prefix('profile')->group(function() {
		Route::get('edit', 'ProfileController@edit')->name('profile.edit');
		Route::put('edit', 'ProfileController@update')->name('profile.update');
		Route::put('password', 'ProfileController@password')->name('profile.password');
	});

	Route::middleware('admin')->group(function() {
		Route::resource('user', 'UserController');
		Route::resource('group', 'UserGroupController');
	});

	/**
	 * Project routes
	 */
	Route::resource('project', 'ProjectController');
	Route::prefix('project')->group(function() {
		
		/**
		 * Contributor routes
		 */
		Route::get('{id}/contributor', 'ProjectContributorController@index')->name('contributor.index');
		Route::post('{id}/contributor', 'ProjectContributorController@store')->name('contributor.store');
		Route::delete('{id}/contributor/{contrib_id}', 'ProjectContributorController@destroy')->name('contributor.destroy');

		/**
		 * Timeline routes
		 */
		Route::get('{id}/timeline', 'ProjectTimelineController@index')->name('timeline.index');
		Route::get('{id}/timeline/create', 'ProjectTimelineController@create')->name('timeline.create');
		Route::post('{id}/timeline', 'ProjectTimelineController@store')->name('timeline.store');
		Route::get('{id}/timeline/{timeline_id}', 'ProjectTimelineController@edit')->name('timeline.edit');
		Route::put('{id}/timeline/{timeline_id}', 'ProjectTimelineController@update')->name('timeline.update');
		Route::delete('{id}/timeline/{timeline_id}', 'ProjectTimelineController@destroy')->name('timeline.destroy');

		// Approve timeline
		Route::get('{id}/timeline/{timeline_id}/approve', 'ProjectTimelineController@toggleApprove')->name('timeline.approve');
		
		// Child timeline
		Route::post('{id}/timeline/child', 'ProjectTimelineController@storeChild')->name('timeline.child.store');

		/**
		 * Timeline comments
		 */
		Route::post('{id}/timeline/{timeline_id}/comment', 'ProjectTimelineCommentController@store')->name('timeline.comment.store');
		Route::delete('{id}/timeline/{timeline_id}/comment/{comment_id}', 'ProjectTimelineCommentController@destroy')->name('timeline.comment.destroy');
	});
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{   
    protected $fillable = [
        'name', 'date_start', 'date_due', 'status', 'created_by', 'updated_by',
    ];

    protected $dates = [
        'date_start', 'date_due',
    ];

    public function contributors()
    {
        return $this->hasMany('App\ProjectContributor');
    }

    public function timelines()
    {
        return $this->hasMany('App\ProjectTimeline');
    }

    public function started_by()
    {
        return $this->belongsTo('App\User', 'created_by');
    }

    public function done_percentage()
    {
        if ($this->timelines->isEmpty()) {
            return '0%';
        }

        $timelines_done = $this->timelines->where('date_done', '!=', null)->count();
        $timelines_done = ($timelines_done / $this->timelines->count()) * 100;
        
        return sprintf('%0.2f', $timelines_done) . "%";
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\ProjectContributor;
use App\User;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    public function index()
    {
        return redirect()->route('home');
    }

    public function create()
    {
        return view('project.create');
    }

    public function store(Request $request)
    {
        $project = Project::create($request->all());

        ProjectContributor::create([
            'project_id' => $project->id,
            'user_id' => auth()->user()->id,
            'created_by' => auth()->user()->id,
            'updated_by' => auth()->user()->id,
        ]);

        return redirect()->route('project.show', $project->id)->withStatus('Project successfully created.');
    }

    public function show($id)
    {
        $project = Project::findOrFail($id);
        $users = User::where('id', '!=', $project->contributors->pluck('user_id')->toArray())->get();
        
        return view('project.show', compact('project', 'users'));
    }

    public function edit($id)
    {
        $project = Project::findOrFail($id);
        
        return view('project.edit', compact('project'));
    }

    public function update(Request $request, $id)
    {
        $project = Project::findOrFail($id);

        $project->update($request->all());

        return redirect()->route('project.show', $project->id)->withStatus('Project information successfully updated.');
    }

    public function destroy($id)
    {
        $project = Project::findOrFail($id);

        $project->delete();
        
        return redirect()->route('home')->withStatus('Project successfully removed.');
    }

    public function settings($id)
    {
        $project = Project::findOrFail($id);
        
        return view('project.settings', compact('project'));
    }
}

resources/views/project/create.blade.php
@extends('layouts.landing', ['title' => __('Projects')])

@section('content')
    @include('layouts.headers.title-landing', ['title' => 'New Project'])

    <div class="container mt--7">
        <div class="row justify-content-center">
            <div class="col-xl-8 order-xl-1">
                <div class="card bg-secondary shadow-sm">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">New Project</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ url()->previous() }}" class="btn btn-sm btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('project.store') }}" autocomplete="off">
                            @csrf
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('Project information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="name">Name</label>
                                    
                                    <input type="text" name="name" id="name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group{{ $errors->has('date_start') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="date_start">Date Start</label>

                                            <input type="date" name="date_start" id="date_start" class="form-control form-control-alternative{{ $errors->has('date_start') ? ' is-invalid' : '' }}" value="{{ old('date_start') }}" required>
        
                                            @if ($errors->has('date_start'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('date_start') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group{{ $errors->has('date_due') ? ' has-danger' : '' }}">
                                            <label class="form-control-label" for="date_due">Date Due</label>

                                            <input type="date" name="date_due" id="date_due" class="form-control form-control-alternative{{ $errors->has('date_due') ? ' is-invalid' : '' }}" value="{{ old('date_due') }}" required>
                                            
                                            @if ($errors->has('date_due'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('date_due') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <input type="hidden" name="status" value="1">
                                <input type="hidden" name="created_by" value="{{ Auth::user()->id }}">
                                <input type="hidden" name="updated_by" value="{{ Auth::user()->id }}">

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">Create new project</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

@push('js')
    <script>
        let dateStart = document.getElementById('date_start');
        let dateDue = document.getElementById('date_due');

        $('#date_start').change(function() {
            dateDue.min = dateStart.value;

            if (dateDue.value < dateStart.value) {
                dateDue.value = dateStart.value;s
            }
        });
    </script>
@endpush

resources/views/project/edit.blade.php
@extends('layouts.app', ['title' => __('Projects')])

@section('content')
    @include('layouts.headers.title', ['title' => 'Project Settings', 'subtitle' => $project->name])

    <div class="container-fluid mt--7">

        @if (in_array(Auth::user()->id, $project->contributors->pluck('user_id')->toArray()))
            <div class="row justify-content-center">
                <div class="col-md-8 mb-4">
                    <div class="card bg-secondary shadow">
                        <div class="card-header bg-white border-0">
                            <h3 class="mb-0">General</h3>
                        </div>

                        <div class="card-body">
                            <form method="post" action="{{ route('project.update', $project->id) }}" autocomplete="off">
                                @csrf
                                @method('PUT')
                                
                                <h6 class="heading-small text-muted mb-4">{{ __('Project information') }}</h6>
                                
                                <div class="pl-lg-4">
                                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                        <label class="form-control-label" for="name">Project name</label>
                                        
                                        <input type="text" name="name" id="name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name" value="{{ $project->name }}" required autofocus>

                                        @if ($errors->has('name'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group{{ $errors->has('date_start') ? ' has-danger' : '' }}">
                                                <label class="form-control-label" for="date_start">Date Start</label>

                                                <input type="date" name="date_start" id="date_start" class="form-control form-control-alternative{{ $errors->has('date_start') ? ' is-invalid' : '' }}" value="{{ $project->date_start->format('Y-m-d') }}" required>
            
                                                @if ($errors->has('date_start'))
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('date_start') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group{{ $errors->has('date_due') ? ' has-danger' : '' }}">
                                                <label class="form-control-label" for="date_due">Date Due</label>

                                                <input type="date" name="date_due" id="date_due" class="form-control form-control-alternative{{ $errors->has('date_due') ? ' is-invalid' : '' }}" value="{{ $project->date_due->format('Y-m-d') }}" max="" required>
                                                
                                                @if ($errors->has('date_due'))
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('date_due') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                    </div>

                                    <input type="hidden" name="status" value="1">
                                    <input type="hidden" name="created_by" value="{{ Auth::user()->id }}">
                                    <input type="hidden" name="updated_by" value="{{ Auth::user()->id }}">

                                    <div class="text-center">
                                        <button type="submit" class="btn btn-success my-4">Save changes</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                @if ($project->started_by->id == Auth::user()->id)
                    <div class="col-md-8">
                        <div class="card bg-secondary shadow">
                            <div class="card-header bg-white border-0">
                                <h3 class="text-danger mb-0">Remove project</h3>
                            </div>

                            <div class="card-body">
                                <div class="d-flex align-items-baseline">
                                    <strong>Removed projects cannot be restored!</strong>

                                    <a href="#" class="btn btn-danger ml-auto" data-toggle="modal" data-target="#removeProject">
                                        Remove project
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        @else
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <div class="card shadow border-0">
                        <div class="card-body text-center">
                            <h2>You don't have access to edit this project</h2>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>

    <!-- Modal -->
    <div class="modal fade" id="removeProject" tabindex="-1" role="dialog" aria-labelledby="removeProjectLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="mb-0">Confirmation</h3>
                </div>
                
                <div class="modal-body">
                    <p class="text-danger font-weight-bold">You are going to remove {{ $project->name }}.</p>
                    <p><strong>Removed projects cannot be restored!</strong></p>

                    <div class="form-group mt-5">
                        <label for="project_name">Please type <span class="text-primary font-weight-bold">{{ $project->name }}</span> to proceed</label>
                        
                        <input type="text" name="project_name" id="project_name" class="form-control">
                    </div>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Cancel</button>
                    
                    <form action="{{ route('project.destroy', $project->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        
                        @if ($project->started_by->id == Auth::user()->id)
                            <button type="submit" id="remove_button" class="btn btn-danger btn-icon" disabled>
                                Confirm
                            </button>
                        @endif
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        let dateStart = document.getElementById('date_start');
        let dateDue = document.getElementById('date_due');
        
        dateDue.min = dateStart.value;

        let inputProject = document.getElementById('project_name');
        let removeButton = document.getElementById('remove_button');


        $('#project_name').keyup(function() {
            if (inputProject.value == "{{ $project->name }}") {
                removeButton.disabled = false;
            } else {
                removeButton.disabled = true;
            }
        });
    </script>
@endpush

resources/views/project/show.blade.php
@extends('layouts.app', ['title' => $project->name])

@section('content')
    @include('layouts.headers.title', ['title' => 'Project Overview', 'subtitle' => $project->name])

    <div class="container-fluid mt--7">
        <div class="row justify-content-center">
            <div class="col-md-4 mb-4">
                <div class="card card-stats shadow border-0 mb-4 mb-lg-0">
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <h5 class="card-title text-uppercase text-muted mb-0">Overall</h5>
                                <span class="h2 font-weight-bold mb-0">
                                    {{ $project->done_percentage() }}
                                </span>
                            </div>
                            <div class="col-auto">
                                <div class="icon icon-shape bg-gradient-primary text-white rounded-circle shadow">
                                    <i class="fa fa-percentage"></i>
                                </div>
                            </div>
                        </div>
                        <p class="mt-3 mb-0 text-muted text-sm">
                            <span class="text-nowrap">Out of</span>
                            <span class="text-success mr-2">
                                {{ $project->timelines->count() }} Timelines
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4 mb-4">
                <div class="card card-stats shadow border-0 mb-4 mb-lg-0">
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <h5 class="card-title text-uppercase text-muted mb-0">Timelines</h5>
                                <span class="h2 font-weight-bold mb-0">
                                    {{ $project->timelines->count() . Str::plural(" Timeline", $project->timelines->count()) }}
                                </span>
                            </div>
                            <div class="col-auto">
                                <div class="icon icon-shape bg-gradient-danger text-white rounded-circle shadow">
                                    <i class="fa fa-project-diagram"></i>
                                </div>
                            </div>
                        </div>
                        <p class="mt-3 mb-0 text-muted text-sm">
                            <span class="text-success mr-2">
                                {{ $project->timelines->where('date_done', '!=', null)->count() . "/" . $project->timelines->count() }}
                            </span>
                            <span class="text-nowrap">Timelines done</span>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card card-stats shadow border-0 mb-4 mb-lg-0">
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <h5 class="card-title text-uppercase text-muted mb-0">Contributors</h5>
                                <span class="h2 font-weight-bold mb-0">
                                    {{ $project->contributors->count() . Str::plural(" Contributor", $project->contributors->count()) }}
                                </span>
                            </div>
                            <div class="col-auto">
                                <div class="icon icon-shape bg-gradient-success text-white rounded-circle shadow">
                                    <i class="fa fa-users"></i>
                                </div>
                            </div>
                        </div>
                        <p class="mt-3 mb-0 text-muted text-sm">
                            <span class="text-nowrap">Started by</span>
                            <span class="text-success mr-2">
                                {{ $project->started_by->name }}
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="card shadow">
            <div class="card-body">

                @if (session('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('status') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                
                <div class="row justify-content-center py-5">
                    <div class="col-md-4 text-center">
                        <div class="icon icon-shape bg-gradient-blue text-white rounded-circle shadow">
                            <i class="fa fa-percentage"></i>
                        </div>
                        <div class="py-3">
                            <span class="font-weight-bold">
                                {{ $project->done_percentage() }}
                            </span>
                            Done
                        </div>
                    </div>
                    <div class="col-md-4 text-center">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="fa fa-project-diagram"></i>
                        </div>
                        <div class="py-3">
                            {{ $project->timelines->count() . Str::plural(" Timeline", $project->timelines->count()) }}
                        </div>
                    </div>
                    <div class="col-md-4 text-center">
                        <div class="icon icon-shape bg-gradient-success text-white rounded-circle shadow">
                            <i class="fa fa-users"></i>
                        </div>
                        <div class="py-3">
                            {{ $project->contributors->count() . Str::plural(" Contributor", $project->contributors->count()) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="mt-5 text-center">
            <form action="{{ route('project.destroy', $project->id) }}" method="post">
                @csrf
                @method('DELETE')

                @if (in_array(Auth::user()->id, $project->contributors->pluck('user_id')->toArray()))
                    <a href="{{ route('project.edit', $project->id) }}" class="btn btn-link btn-icon">
                        <i class="fa fa-pen"></i> Edit Project
                    </a>
                @endif
                
                @if ($project->started_by->id == Auth::user()->id)
                    <button type="submit" class="btn btn-link text-danger btn-icon"
                        onclick="return confirm('Are you sure you want to delete this project? this action cannot be reverted')">
                        <i class="fa fa-trash"></i> Delete Project
                    </button>
                @endif
            </form>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $('#dateStartNow').click(function() {
            var dateStart = document.getElementById('date_start');
            dateStart.value = "{{ now()->format('Y-m-d') }}";
        });

        $('#dateDueNow').click(function() {
            var dateDue = document.getElementById('date_end');
            dateDue.value = "{{ now()->format('Y-m-d') }}";
        });
    </script>
@endpush