routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
	/**
	 * Profile routes
	 */
	Route::prefix('profile')->group(function() {
		Route::get('edit', 'ProfileController@edit')->name('profile.edit');
		Route::put('edit', 'ProfileController@update')->name('profile.update');
		Route::put('password', 'ProfileController@password')->name('profile.password');
	});

	Route::middleware('admin')->group(function() {
		Route::resource('user', 'UserController');
		Route::resource('group', 'UserGroupController');
	});

	/**
	 * Project routes
	 */
	Route::resource('project', 'ProjectController');
	Route::prefix('project')->group(function() {
		
		/**
		 * Contributor routes
		 */
		Route::get('{id}/contributor', 'ProjectContributorController@index')->name('contributor.index');
		Route::post('{id}/contributor', 'ProjectContributorController@store')->name('contributor.store');
		Route::delete('{id}/contributor/{contrib_id}', 'ProjectContributorController@destroy')->name('contributor.destroy');

		/**
		 * Timeline routes
		 */
		Route::get('{id}/timeline', 'ProjectTimelineController@index')->name('timeline.index');
		Route::get('{id}/timeline/create', 'ProjectTimelineController@create')->name('timeline.create');
		Route::post('{id}/timeline', 'ProjectTimelineController@store')->name('timeline.store');
		Route::get('{id}/timeline/{timeline_id}', 'ProjectTimelineController@edit')->name('timeline.edit');
		Route::put('{id}/timeline/{timeline_id}', 'ProjectTimelineController@update')->name('timeline.update');
		Route::delete('{id}/timeline/{timeline_id}', 'ProjectTimelineController@destroy')->name('timeline.destroy');

		// Approve timeline
		Route::get('{id}/timeline/{timeline_id}/approve', 'ProjectTimelineController@toggleApprove')->name('timeline.approve');
		
		// Child timeline
		Route::post('{id}/timeline/child', 'ProjectTimelineController@storeChild')->name('timeline.child.store');

		/**
		 * Timeline comments
		 */
		Route::post('{id}/timeline/{timeline_id}/comment', 'ProjectTimelineCommentController@store')->name('timeline.comment.store');
		Route::delete('{id}/timeline/{timeline_id}/comment/{comment_id}', 'ProjectTimelineCommentController@destroy')->name('timeline.comment.destroy');
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'username', 'password', 'user_group_id', 'status'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function group()
    {
        return $this->belongsTo('App\UserGroup', 'user_group_id');
    }

    public function projects()
    {
        return $this->hasMany('App\Project', 'created_by');
    }

    public function contributes()
    {
        return $this->hasMany('App\ProjectContributor');
    }

    public function comments()
    {
        return $this->hasMany('App\ProjectTimelineComment', 'created_by');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\UserGroup;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        
        return view('users.index', compact('users'));
    }

    public function create()
    {
        $user_groups = UserGroup::all();
        
        return view('users.create', compact('user_groups'));

        \App\maklonProject::where([
            ['status_approval', 1], 
            ['id', $request->id]]
        )->get();
    }

    public function store(UserRequest $request, User $model)
    {
        $model->create(
            $request->merge(['password' => Hash::make($request->get('password'))])->all()
        );

        return redirect()->route('user.index')->withStatus(__('User successfully created.'));
    }

    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('users.show', compact('user'));
    }

    public function edit(User $user)
    {
        $user_groups = UserGroup::all();
        
        return view('users.edit', compact('user', 'user_groups'));
    }

    public function update(UserRequest $request, User $user)
    {
        $user->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$request->get('password') ? '' : 'password']
        ));

        return redirect()->route('user.index')->withStatus(__('User successfully updated.'));
    }

    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('user.index')->withStatus(__('User successfully deleted.'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.landing', ['title' => __('User Management')])

@section('content')
    @include('layouts.headers.title-landing', ['title' => 'Add User'])

    <div class="container mt--7">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Add User</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('user.store') }}" autocomplete="off">
                            @csrf
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('User information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="name">Name</label>
                                    <input type="text" name="name" id="name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('username') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="username">Username</label>
                                    
                                    <input type="text" name="username" id="username" class="form-control form-control-alternative{{ $errors->has('username') ? ' is-invalid' : '' }}" placeholder="Username" value="{{ old('username') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="email">Email</label>
                                    <input type="email" name="email" id="email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('user_group_id') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="user_group_id">User Group</label>

                                    <select name="user_group_id" id="user_group_id" class="form-control form-control-alternative{{ $errors->has('user_group_id') ? ' is-invalid' : '' }}" placeholder="wayoo">
                                        @foreach ($user_groups as $r)
                                            <option value="{{ $r->id }}">{{ $r->name }}</option>
                                        @endforeach
                                    </select>

                                    @if ($errors->has('user_group_id'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('user_group_id') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="password">{{ __('Password') }}</label>
                                    <input type="password" name="password" id="password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Password') }}" value="" required>
                                    
                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="password_confirmation">{{ __('Confirm Password') }}</label>
                                    <input type="password" name="password_confirmation" id="password_confirmation" class="form-control form-control-alternative" placeholder="{{ __('Confirm Password') }}" value="" required>
                                </div>

                                <input type="hidden" name="status" value="1">

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">SAVE</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.landing', ['title' => __('User Management')])

@section('content')
    @include('layouts.headers.title-landing', ['title' => 'Edit User'])

    <div class="container mt--7">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Edit User</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('user.update', $user) }}" autocomplete="off">
                            @csrf
                            @method('PUT')
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('User information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="name">Name</label>
                                    <input type="text" name="name" id="name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name" value="{{ $user->name }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('username') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="username">Username</label>
                                    
                                    <input type="text" name="username" id="username" class="form-control form-control-alternative{{ $errors->has('username') ? ' is-invalid' : '' }}" placeholder="Username" value="{{ $user->username }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="email">Email</label>
                                    <input type="email" name="email" id="email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ $user->email }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('user_group_id') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="user_group_id">User Group</label>

                                    <select name="user_group_id" id="user_group_id" class="form-control form-control-alternative{{ $errors->has('user_group_id') ? ' is-invalid' : '' }}" placeholder="wayoo">
                                        @foreach ($user_groups as $r)
                                            <option {{ $user->user_group_id == $r->id ? 'selected' : '' }} value="{{ $r->id }}">{{ $r->name }}</option>
                                        @endforeach
                                    </select>

                                    @if ($errors->has('user_group_id'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('user_group_id') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <input type="hidden" name="status" value="1">
                            </div>

                            <h6 class="heading-small text-muted mb-4">
                                Change Password <span class="text-danger">(Optional)</span>
                            </h6>
                            
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="password">{{ __('Password') }}</label>
                                    <input type="password" name="password" id="password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Password') }}" value="">
                                    
                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="password_confirmation">{{ __('Confirm Password') }}</label>
                                    <input type="password" name="password_confirmation" id="password_confirmation" class="form-control form-control-alternative" placeholder="{{ __('Confirm Password') }}" value="">
                                </div>
                            </div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-success mt-4">SAVE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.landing', ['title' => __('User Management')])

@section('content')
    @include('layouts.headers.title-landing', ['title' => 'List of Users'])

    <div class="container mt--7">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Users</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">Add user</a>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered align-items-center table-flush" id="table">
                                <thead class="thead-light">
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Username</th>
                                        <th>User Group</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($users as $user)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>
                                                <a href="mailto:{{ $user->email }}" target="_blank">{{ $user->email }}</a>
                                            </td>
                                            <td>{{ $user->username }}</td>
                                            <td>
                                                <a href="{{ route('group.show', $user->group->id) }}">{{ $user->group->name }}</a>
                                            </td>
                                            <td class="text-right">
                                                <div class="dropdown">
                                                    <a class="btn btn-primary btn-icon-only" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fas fa-ellipsis-v"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                        @if ($user->id != auth()->id())
                                                            <form action="{{ route('user.destroy', $user) }}" method="post">
                                                                @csrf
                                                                @method('delete')
                                                                
                                                                <a class="dropdown-item" href="{{ route('user.edit', $user) }}">Edit</a>
                                                                <button type="button" class="dropdown-item" onclick="confirm('Are you sure you want to delete this user?') ? this.parentElement.submit() : ''">
                                                                    {{ __('Delete') }}
                                                                </button>
                                                            </form>    
                                                        @else
                                                            <a class="dropdown-item" href="{{ route('profile.edit') }}">Edit</a>
                                                        @endif
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.landing', ['title' => __('User Profile')])

@section('content')
    @include('layouts.headers.title-landing', [
        'title' => 'Hello ' . Auth::user()->name,
    ])

    <div class="container mt--7">
        <div class="row justify-content-center">
            <div class="col-xl-6 order-xl-2 mb-5 mb-xl-0">
                <div class="card card-profile shadow">
                    <div class="card-body pt-0 pt-md-4">
                        <div class="text-center mt-3">
                            <h2 class="card-title mb-3">{{ Auth::user()->name }}</h2>

                            <div class="card-subtitle text-primary">
                                {{ Auth::user()->user_group->name }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="card-profile-stats d-flex justify-content-center">
                                    <div>
                                        <span class="heading">{{ Auth::user()->contributes->count() }}</span>
                                        <span class="description">{{ Str::plural('Contribute', Auth::user()->contributes->count()) }}</span>
                                    </div>
                                    <div>
                                        <span class="heading">{{ Auth::user()->projects->count() }}</span>
                                        <span class="description">{{ Str::plural('Project', Auth::user()->contributes->count()) . " started" }}</span>
                                    </div>
                                    <div>
                                        <span class="heading">89</span>
                                        <span class="description">{{ __('Comments') }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection