routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
	/**
	 * Profile routes
	 */
	Route::prefix('profile')->group(function() {
		Route::get('edit', 'ProfileController@edit')->name('profile.edit');
		Route::put('edit', 'ProfileController@update')->name('profile.update');
		Route::put('password', 'ProfileController@password')->name('profile.password');
	});

	Route::middleware('admin')->group(function() {
		Route::resource('user', 'UserController');
		Route::resource('group', 'UserGroupController');
	});

	/**
	 * Project routes
	 */
	Route::resource('project', 'ProjectController');
	Route::prefix('project')->group(function() {
		
		/**
		 * Contributor routes
		 */
		Route::get('{id}/contributor', 'ProjectContributorController@index')->name('contributor.index');
		Route::post('{id}/contributor', 'ProjectContributorController@store')->name('contributor.store');
		Route::delete('{id}/contributor/{contrib_id}', 'ProjectContributorController@destroy')->name('contributor.destroy');

		/**
		 * Timeline routes
		 */
		Route::get('{id}/timeline', 'ProjectTimelineController@index')->name('timeline.index');
		Route::get('{id}/timeline/create', 'ProjectTimelineController@create')->name('timeline.create');
		Route::post('{id}/timeline', 'ProjectTimelineController@store')->name('timeline.store');
		Route::get('{id}/timeline/{timeline_id}', 'ProjectTimelineController@edit')->name('timeline.edit');
		Route::put('{id}/timeline/{timeline_id}', 'ProjectTimelineController@update')->name('timeline.update');
		Route::delete('{id}/timeline/{timeline_id}', 'ProjectTimelineController@destroy')->name('timeline.destroy');

		// Approve timeline
		Route::get('{id}/timeline/{timeline_id}/approve', 'ProjectTimelineController@toggleApprove')->name('timeline.approve');
		
		// Child timeline
		Route::post('{id}/timeline/child', 'ProjectTimelineController@storeChild')->name('timeline.child.store');

		/**
		 * Timeline comments
		 */
		Route::post('{id}/timeline/{timeline_id}/comment', 'ProjectTimelineCommentController@store')->name('timeline.comment.store');
		Route::delete('{id}/timeline/{timeline_id}/comment/{comment_id}', 'ProjectTimelineCommentController@destroy')->name('timeline.comment.destroy');
	});
});

app/UserGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserGroup extends Model
{
    protected $fillable = [
        'name', 'status',
    ];

    public function users()
    {
        return $this->hasMany('App\User');
    }
}

app/Http/Controllers/UserGroupController.php
<?php

namespace App\Http\Controllers;

use App\UserGroup;
use Illuminate\Http\Request;

class UserGroupController extends Controller
{
    public function index()
    {
        $groups = UserGroup::all();
        
        return view('user_group.index', compact('groups'));
    }

    public function create()
    {
        return view('user_group.create');
    }

    public function store(Request $request)
    {
        UserGroup::create($request->all());

        return redirect()->route('group.index')->withStatus('Group successfully created.');
    }

    public function show($id)
    {
        $group = UserGroup::findOrFail($id);

        return view('user_group.show', compact('group'));
    }

    public function edit($id)
    {
        $group = UserGroup::findOrFail($id);

        return view('user_group.edit', compact('group'));
    }

    public function update(Request $request, $id)
    {
        $group = UserGroup::findOrFail($id);

        $group->update($request->all());

        return redirect()->route('group.index')->withStatus('Group successfully updated.');
    }

    public function destroy($id)
    {
        $group = UserGroup::findOrFail($id);

        $group->delete();

        return redirect()->route('group.index')->withStatus('Group successfully deleted.');
    }
}

resources/views/user_group/create.blade.php
@extends('layouts.landing', ['title' => __('User Group')])

@section('content')
    @include('layouts.headers.title-landing', ['title' => 'Add Group'])

    <div class="container mt--7">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Add Group</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ url()->previous() }}" class="btn btn-sm btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('group.store') }}" autocomplete="off">
                            @csrf
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('Group information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="name">Name</label>
                                    
                                    <input type="text" name="name" id="name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <input type="hidden" name="status" value="1">

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">SAVE</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/user_group/edit.blade.php
@extends('layouts.landing', ['title' => __('User Group')])

@section('content')
    @include('layouts.headers.title-landing', ['title' => 'Edit Group'])

    <div class="container mt--7">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Edit Group</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ url()->previous() }}" class="btn btn-sm btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('group.update', $group->id) }}" autocomplete="off">
                            @csrf
                            @method('PUT')
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('Group information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="name">Name</label>
                                    
                                    <input type="text" name="name" id="name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name" value="{{ $group->name }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <input type="hidden" name="status" value="1">

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">SAVE</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/user_group/index.blade.php
@extends('layouts.landing', ['title' => __('User Group')])

@section('content')
    @include('layouts.headers.title-landing', ['title' => 'List of Groups'])

    <div class="container mt--7">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Groups</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('group.create') }}" class="btn btn-sm btn-primary">Add group</a>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover align-items-center table-flush" id="table">
                                <thead class="thead-light">
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Users count</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($groups as $group)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>
                                                <a href="{{ route('group.show', $group->id) }}">{{ $group->name }}</a>
                                            </td>
                                            <td>{{ $group->users->count() }}</td>
                                            <td class="text-right">
                                                <div class="dropdown">
                                                    <a class="btn btn-primary btn-icon-only {{ $group->name == 'Administrator' ? 'disabled' : '' }}" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fas fa-ellipsis-v"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                        <form action="{{ route('group.destroy', $group) }}" method="post">
                                                            @csrf
                                                            @method('DELETE')
                                                            
                                                            <a class="dropdown-item" href="{{ route('group.edit', $group) }}">Edit</a>

                                                            <button type="button" class="dropdown-item" onclick="confirm('Are you sure you want to delete this group?') ? this.parentElement.submit() : ''">
                                                                Delete
                                                            </button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/user_group/show.blade.php
@extends('layouts.landing', ['title' => __('User Group')])

@section('content')
    @include('layouts.headers.title-landing', ['title' => 'Group Information', 'subtitle' => $group->name])

    <div class="container-fluid mt--7">
        <div class="row justify-content-center">
            <div class="col-xl-8 order-xl-1">
                <div class="card shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0"><span class="text-muted">Group |</span> List of Users in {{ $group->name }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ url()->previous() }}" class="btn btn-sm btn-primary">Back</a>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-bordered align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Username</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if ($group->users->isNotEmpty())
                                    @foreach ($group->users as $user)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>
                                                <a href="mailto:{{ $user->email }}" target="_blank">{{ $user->email }}</a>
                                            </td>
                                            <td>{{ $user->username }}</td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="4" align="center">
                                            <div class="text-danger mb-2">No users found</div>
                                            <a href="{{ route('user.create') }}" class="btn btn-success btn-sm">Add one instead</a>
                                        </td>
                                    </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection